name: Run application tests
run-name: Run application tests

on: 
    push:
    pull_request:
        types: [opened, synchronize]
        
jobs:
    unit-test:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code
              uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

            - name: Setup Node.js
              uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
              with:
                node-version: 18

            - name: Install pnpm
              uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598
              with:
                version: 8
                run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: Setup pnpm cache
              uses: actions/cache@v3
              with:
                path: ${{ env.STORE_PATH }}
                key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                restore-keys: |
                    ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install

            - name: Run unit tests
              run: pnpm test
